# Set the language Travis CI should expect.
language: node_js

# Set the Node.js version you’d like Travis to use. Add more versions as you like.
node_js:
- 14

# Cache all npm dependencies so Travis CI only installs dependencies once.
# For multiple builds, caching all npm dependencies enables your builds to run faster.
cache: npm

# Configure the build cycles to tell Travis CI to install all dependencies.
# You can also add other dependencies you like Travis to install globally.
install: # Hook provided by Travis CI
- npm install

# Tell Travis CI to run the test for your Node application
script:
- npm test 

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - export PATH=$PATH:C:\Program Files\heroku\bin

before_deploy:
  - heroku --version
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.8.0

deploy:
  provider: heroku
  skip-cleanup: true
  api_key: $HEROKU_TOKEN
  app: node-travis-app
